version: '3'

services:
  web:
    build: .  # Dit zal de Dockerfile in de huidige map gebruiken
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: classifiedads
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db
